name: learn-github-actions
on:
  pull_request:
    branches:
      - develop
jobs:
  ut:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Prepare node
        uses: actions/setup-node@v2
        with:
          node-version: '12'
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npm run test